[client]
toolbarMode = "minimal"

[logger]
level = "warning"

[theme]
base="dark"
primaryColor="#d10000"      
backgroundColor="#111111"   
secondaryBackgroundColor="#1a1a1a"  
textColor="#ffffff"   
font="sans serif" 

[browser]
gatherUsageStats = false